#ifndef VERSION_H
#define VERSION_H
 
#define MAGICPAD_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"
#define MAGICPAD_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define MAGICPAD_VERSION_PATCH "@PROJECT_VERSION_PATCH@"
#define MAGICPAD_VERSION_STR "@PROJECT_VERSION_STR@"

#define OPENCV_VERSION "@OpenCV_VERSION@"
 
#endif // VERSION_H
